<div class="__act_item __act_colors">
    <div class="draw_rect child-item size-auto child-item-btn">
        <img width="16" height="16" src="<%= ASSETS_URL %>img/square.svg">
    </div>
    <div class="draw_circle child-item size-auto child-item-btn">
        <img width="16" height="16" src="<%= ASSETS_URL %>img/round.svg">
    </div>
    <div class="draw_line child-item size-auto child-item-btn">
        <img width="16" height="16" src="<%= ASSETS_URL %>img/line.svg">
    </div>
    <div class="draw_ellipse child-item size-auto child-item-btn">
        <img width="16" height="16" src="<%= ASSETS_URL %>img/oval.svg">
    </div>
    <div class="draw_arrow child-item size-auto child-item-btn">
        <img width="16" height="16" src="<%= ASSETS_URL %>img/arrow.svg">
    </div>
</div>